//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escuela_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Ciudad = new HashSet<Ciudad>();
        }
    
        public int ID_Estado { get; set; }
        public string nombre { get; set; }
        public int pais { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual Pais Pais1 { get; set; }
    }
}
